# Generated by Django 6.0.3 on 2026-03-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="integrationconnection",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="integrationconnection",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integration_connections",
                to="projects.project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="integrationconnection",
            unique_together={("project", "provider", "external_account_id")},
        ),
    ]
