# Generated by Django 6.0.3 on 2026-03-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_alter_integrationconnection_unique_together_and_more"),
        ("projects", "0002_assign_existing_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconnection",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integration_connections",
                to="projects.project",
            ),
        ),
    ]
