# Generated by Django 6.0.3 on 2026-03-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0002_socialmediapost_ai_instruction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediasettings",
            name="enable_facebook",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="socialmediasettings",
            name="enable_instagram",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="socialmediasettings",
            name="enable_linkedin",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="socialmediasettings",
            name="enable_x",
            field=models.BooleanField(default=True),
        ),
    ]
