# Generated by Django 6.0.3 on 2026-03-30 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("social_media", "0003_change_platform_defaults_to_true"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapost",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_media_posts",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="socialmediasettings",
            name="project",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_media_settings",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="socialmediasettings",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_media_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
