# Generated by Django 6.0.3 on 2026-03-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_assign_existing_data"),
        (
            "social_media",
            "0004_socialmediapost_project_socialmediasettings_project_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediapost",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_media_posts",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="socialmediasettings",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_media_settings",
                to="projects.project",
            ),
        ),
    ]
