# Generated by Django 6.0.3 on 2026-03-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0006_copy_platform_settings_to_project"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialMediaSettings",
        ),
    ]
