# Generated by Django 6.0.3 on 2026-05-01 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "media_library",
            "0012_remove_image_image_group_remove_imagegroup_project_and_more",
        ),
        ("social_media", "0009_add_publishing_status_and_published_url"),
    ]

    operations = [
        # Clear references to old media_library.Image rows before changing FKs
        migrations.RunSQL(
            sql="DELETE FROM social_media_socialmediaplatformmedia; DELETE FROM social_media_socialmediapostmedia; DELETE FROM social_media_socialmediapostseedimage;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="socialmediaplatformmedia",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="media_library.media"
            ),
        ),
        migrations.AlterField(
            model_name="socialmediapostmedia",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="media_library.media"
            ),
        ),
        migrations.AlterField(
            model_name="socialmediapostseedimage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="media_library.media"
            ),
        ),
    ]
