# Generated by Django 6.0.3 on 2026-05-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0010_alter_socialmediaplatformmedia_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="socialmediaplatformmedia",
            old_name="image",
            new_name="media",
        ),
        migrations.RenameField(
            model_name="socialmediapostmedia",
            old_name="image",
            new_name="media",
        ),
        migrations.RenameField(
            model_name="socialmediapostseedimage",
            old_name="image",
            new_name="media",
        ),
        migrations.AlterField(
            model_name="socialmediapostseedimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seed_media",
                to="social_media.socialmediapost",
            ),
        ),
    ]
