# Generated by Django 6.0.3 on 2026-05-03 17:11

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0012_alter_socialmediapost_post_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediapost",
            name="topic",
            field=core.fields.TruncatingCharField(blank=True, max_length=2000),
        ),
    ]
