# Generated by Django 6.0.3 on 2026-03-30 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0002_alter_brand_logo"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="project",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
