# Generated by Django 6.0.3 on 2026-03-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0003_brand_project_alter_brand_user"),
        ("projects", "0002_assign_existing_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand",
                to="projects.project",
            ),
        ),
    ]
