# Generated by Django 6.0.3 on 2026-04-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0004_alter_brand_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="language",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
