# Generated by Django 6.0.3 on 2026-04-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0005_alter_brand_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="fonts",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="primary_color",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="brand",
            name="secondary_color",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="brand",
            name="target_audience",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="tone_of_voice",
            field=models.TextField(blank=True),
        ),
    ]
