# Generated by Django 6.0.3 on 2026-05-01 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0007_processing_status"),
        (
            "media_library",
            "0012_remove_image_image_group_remove_imagegroup_project_and_more",
        ),
    ]

    operations = [
        # Clear old FK references to imagegroup before changing the FK to mediagroup
        # (data migration: existing logo references are invalid since imagegroup data
        #  is not carried over to mediagroup — acceptable since app is not in production)
        migrations.RunSQL(
            sql="UPDATE brand_brand SET logo_id = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logo_brands",
                to="media_library.mediagroup",
            ),
        ),
    ]
