# Generated by Django 6.0.3 on 2026-03-30 18:08

from django.db import migrations


def assign_existing_data(apps, schema_editor):
    User = apps.get_model('accounts', 'CustomUser')
    Project = apps.get_model('projects', 'Project')
    Brand = apps.get_model('brand', 'Brand')
    IntegrationConnection = apps.get_model('integrations', 'IntegrationConnection')
    ImageGroup = apps.get_model('media_library', 'ImageGroup')
    SocialMediaPost = apps.get_model('social_media', 'SocialMediaPost')
    SocialMediaSettings = apps.get_model('social_media', 'SocialMediaSettings')

    for user in User.objects.all():
        project = Project.objects.create(
            owner=user,
            name=user.company_name or 'My Project',
        )
        Brand.objects.filter(user=user).update(project=project)
        IntegrationConnection.objects.filter(user=user).update(project=project)
        ImageGroup.objects.filter(user=user).update(project=project)
        SocialMediaPost.objects.filter(user=user).update(project=project)
        SocialMediaSettings.objects.filter(user=user).update(project=project)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("brand", "0003_brand_project_alter_brand_user"),
        ("integrations", "0002_alter_integrationconnection_unique_together_and_more"),
        ("media_library", "0008_imagegroup_project"),
        ("social_media", "0004_socialmediapost_project_socialmediasettings_project_and_more"),
    ]

    operations = [
        migrations.RunPython(assign_existing_data, migrations.RunPython.noop),
    ]
