# Generated by Django 6.0.3 on 2026-03-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_assign_existing_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="enable_facebook",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="enable_instagram",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="enable_linkedin",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="enable_x",
            field=models.BooleanField(default=True),
        ),
    ]
