# Generated by Django 5.2 on 2026-03-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0002_imagegroup_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="external_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media_library/images/%Y/%m/"
            ),
        ),
    ]
