# Generated by Django 5.2 on 2026-03-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0003_image_external_url_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagegroup",
            name="type",
            field=models.CharField(
                choices=[("product", "Product"), ("manual", "Manual")],
                default="manual",
                max_length=20,
            ),
        ),
    ]
