# Generated by Django 6.0.3 on 2026-03-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0007_image_image_type_alter_imagegroup_type"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagegroup",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_groups",
                to="projects.project",
            ),
        ),
    ]
