# Generated by Django 6.0.3 on 2026-03-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0008_imagegroup_project"),
        ("projects", "0002_assign_existing_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagegroup",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_groups",
                to="projects.project",
            ),
        ),
    ]
