# Generated by Django 6.0.3 on 2026-05-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0008_alter_brand_logo"),
        (
            "media_library",
            "0012_remove_image_image_group_remove_imagegroup_project_and_more",
        ),
        ("social_media", "0010_alter_socialmediaplatformmedia_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="ImageGroup",
        ),
    ]
