# Generated by Django 6.0.3 on 2026-05-03 17:11

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0016_increase_external_url_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediagroup",
            name="title",
            field=core.fields.TruncatingCharField(max_length=2000),
        ),
    ]
