# Generated by Django 6.0.3 on 2026-04-01 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditspend",
            name="grant",
        ),
        migrations.CreateModel(
            name="CreditAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="credits.creditgrant",
                    ),
                ),
                (
                    "spend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="credits.creditspend",
                    ),
                ),
            ],
            options={
                "ordering": ["spend_id"],
            },
        ),
    ]
